#!/bin/bash
function options {
	echo “”
	echo “1. Rock”
	echo “2. Paper”
	echo “3. Scissors”
	echo “4. Done”
	echo “”
}
function human {
	read -p “Your choice [1-4]?” human
	if (( “$human” == 1 )); then
		echo “You chose 1. Rock”
	elif (( “$human” == 2 )); then
		echo “You chose 2. Paper”
	elif (( $human == 3 )); then
		echo “You chose 3. Scissors”
	elif (( $human == 4 )); then
		echo “”
		echo “Bye”
	fi
}
function computer {
	if (( $human != 4 )); then
		computer=$(( ( RANDOM % 3 ) + 1 ))
		if (( “$computer” == 1 )); then
			echo “Computer chose 1. Rock”
		elif (( “$computer” == 2 )); then
			echo “Computer chose 2. Paper”
		elif (( “$computer” == 3 )); then
			echo “Computer chose 3. Scissors”
		fi
	fi
}
function game {
	if (( $human == $computer )); then
		echo “You tied. Try again.”
	elif (( $human == 1 && $computer == 3 )); then
		echo “You win.”
	elif (( $human == 3 && $computer == 1 )); then
		echo “You lost. Try again.”
	elif (( $human == 3 && $computer == 2 )); then
		echo “You win.”
	elif (( $human == 2 && $computer == 3 )); then
		echo “You lost. Try again.”
	elif (( $human == 2 && $computer == 1 )); then
		echo “You win.”
	elif (9 $human == 1 && $computer == 2 )); then
		echo “You lost. Try again.”
	fi
}
function loop {
 	while [[ $human < 5 ]]; do
		if (( $human == 1 || $human == 2 || $human == 3 )); then
			main
		elif (( $human == 4 )); then
			break
		fi
	done
}

main
loop
  
